"""Report service — generates a comprehensive analysis report.

Aggregates data from quote, indicators, sentiment, prediction, and signal
services. Includes mode/source/limitations for full transparency.
"""

from typing import Dict, Any
from datetime import datetime, timezone

from app.services.cache_service import set_cached_payload


def generate_report(symbol: str, quote: Dict[str, Any], indicators: Dict[str, Any],
                    sentiment: Dict[str, Any], prediction: Dict[str, Any], signal: Dict[str, Any]) -> Dict[str, Any]:
    """Generate a full analysis report combining all service outputs."""

    quote_meta = quote.get("_meta", {})
    ind_meta = indicators.get("_meta", {})
    sent_meta = sentiment.get("_meta", {})
    pred_meta = prediction.get("_meta", {})
    sig_meta = signal.get("_meta", {})

    # Determine overall mode
    modes = [
        quote_meta.get("mode", "unknown"),
        ind_meta.get("mode", "unknown"),
        sent_meta.get("mode", "unknown"),
        pred_meta.get("mode", "unknown"),
        sig_meta.get("mode", "unknown"),
    ]
    if all(m == "real" for m in modes):
        overall_mode = "real"
    elif any(m == "real" for m in modes):
        overall_mode = "mixed"
    else:
        overall_mode = "fallback"

    # Build summary
    summary = f"{symbol} is currently showing a {signal.get('signal_label', 'Neutral / Wait')} setup. "

    if indicators.get("available", False):
        summary += f"Current price: {quote.get('price', 0)}, with a {indicators.get('price_change_pct', 0)}% change over the tracked period. "
        summary += f"Technical indicators point to a {indicators.get('trend', 'Neutral')} trend. "

    summary += f"Sentiment: {sentiment.get('overall_sentiment', 'Neutral')}. "

    # Collect limitations
    limitations = []
    if quote_meta.get("mode") == "demo":
        limitations.append("Market data is DEMO — yfinance unavailable")
    if sent_meta.get("news_mode") == "demo":
        limitations.append("Sentiment based on demo news — Finnhub key not set")
    if prediction.get("model_used") == "Simple_Trend_Projection":
        limitations.append("Prediction uses simple trend projection, not ML")

    payload = {
        "company_summary": f"Automated analysis report for {symbol}.",
        "market_performance": f"Latest price: {quote.get('price', 0)}, Volume: {quote.get('volume', 0)}",
        "technical_analysis": f"RSI: {indicators.get('rsi', 'N/A')}, Trend: {indicators.get('trend', 'N/A')}",
        "sentiment_analysis": f"Score: {sentiment.get('sentiment_score', 0)} ({sentiment.get('overall_sentiment', 'Neutral')})",
        "prediction_insight": f"Projected direction: {prediction.get('prediction_direction', 'Unknown')}",
        "risk_factors": signal.get("risk_flags", []),
        "final_analysis_summary": summary,
        "data_source_list": [
            f"yfinance ({quote_meta.get('mode', 'unknown')})",
            f"Finnhub/Fallback ({sent_meta.get('news_source', 'unknown')})",
            f"VADER ({sent_meta.get('mode', 'unknown')})",
            f"Trend Projection ({pred_meta.get('mode', 'unknown')})",
        ],
        "limitations": limitations,
        "disclaimer": "This report is generated by AI for analysis and educational purposes only. It does not constitute financial advice.",
        "_meta": {
            "mode": overall_mode,
            "source": "stocksee_report_engine",
            "data_modes": {
                "quote": quote_meta.get("mode", "unknown"),
                "indicators": ind_meta.get("mode", "unknown"),
                "sentiment": sent_meta.get("mode", "unknown"),
                "prediction": pred_meta.get("mode", "unknown"),
                "signal": sig_meta.get("mode", "unknown"),
            },
            "generated_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        },
    }
    
    set_cached_payload(symbol, "report", payload, overall_mode, "stocksee_report_engine", 360)
    return payload
