"""Report service — generates a comprehensive analysis report.

Aggregates data from quote, indicators, sentiment, prediction, and signal
services. Includes mode/source/limitations for full transparency.
Formats the outputs to match the intelligence core engine while strictly
preserving the legacy JSON API contract.
"""

from typing import Dict, Any
from datetime import datetime, timezone

from app.services.cache_service import set_cached_payload


def generate_report(symbol: str, quote: Dict[str, Any], indicators: Dict[str, Any],
                    sentiment: Dict[str, Any], prediction: Dict[str, Any], signal: Dict[str, Any]) -> Dict[str, Any]:
    """Generate a full analysis report combining all service outputs."""

    quote_meta = quote.get("_meta", {})
    ind_meta = indicators.get("_meta", {})
    sent_meta = sentiment.get("_meta", {})
    pred_meta = prediction.get("_meta", {})
    sig_meta = signal.get("_meta", {})

    # Determine overall mode
    modes = [
        quote_meta.get("mode", "unknown"),
        ind_meta.get("mode", "unknown"),
        sent_meta.get("mode", "unknown"),
        pred_meta.get("mode", "unknown"),
        sig_meta.get("mode", "unknown"),
    ]
    if all(m == "real" for m in modes):
        overall_mode = "real"
    elif any(m == "real" for m in modes):
        overall_mode = "mixed"
    else:
        overall_mode = "fallback"

    # Build final analysis summary explicitly exposing evidence and conflicts
    summary_parts = []
    summary_parts.append(f"{symbol} is currently showing a {signal.get('signal_label', 'Neutral / Wait')} setup with {signal.get('confidence', 'Low')} confidence.")
    
    if signal.get("bullish_evidence"):
        summary_parts.append("Bullish Evidence: " + "; ".join(signal.get("bullish_evidence", [])))
    if signal.get("bearish_evidence"):
        summary_parts.append("Bearish Evidence: " + "; ".join(signal.get("bearish_evidence", [])))
    if signal.get("conflicts"):
        summary_parts.append("Key Conflicts Detected: " + "; ".join(signal.get("conflicts", [])))
        
    summary = " | ".join(summary_parts)

    # Collect limitations
    limitations = []
    if quote_meta.get("mode") == "demo":
        limitations.append("Market data is DEMO — yfinance unavailable")
    if sent_meta.get("news_mode") == "demo":
        limitations.append("Sentiment based on demo news — Finnhub key not set")
    if prediction.get("model_used") != "None":
        limitations.append(prediction.get("limitations", "No prediction model loaded"))

    payload = {
        "company_summary": f"Automated decision-support analysis for {symbol}.",
        "market_performance": f"Latest price: {quote.get('price', 0)}, Volume: {quote.get('volume', 0)}",
        "technical_analysis": f"Trend: {indicators.get('trend', 'N/A')}, RSI: {indicators.get('rsi', 'N/A')}",
        "sentiment_analysis": f"Score: {sentiment.get('sentiment_score', 0)} ({sentiment.get('overall_sentiment', 'Neutral')})",
        
        # Backward compatibility: Mapped to the new scenario projection
        "prediction_insight": prediction.get("scenario_projection", "No scenario established."),
        
        # Risk factors now pull from the structured risk engine
        "risk_factors": [f"Risk Level: {signal.get('risk_level', 'UNKNOWN')}"] + signal.get("risk_flags", []),
        
        "final_analysis_summary": summary,
        "data_source_list": [
            f"yfinance ({quote_meta.get('mode', 'unknown')})",
            f"Finnhub/Fallback ({sent_meta.get('news_source', 'unknown')})",
            f"VADER ({sent_meta.get('mode', 'unknown')})",
            f"Scenario Projection ({pred_meta.get('mode', 'unknown')})",
        ],
        "limitations": limitations,
        "disclaimer": "This report is generated by deterministic analysis for educational purposes only. It does not constitute financial advice.",
        "_meta": {
            "mode": overall_mode,
            "source": "stocksee_intelligence_core",
            "data_modes": {
                "quote": quote_meta.get("mode", "unknown"),
                "indicators": ind_meta.get("mode", "unknown"),
                "sentiment": sent_meta.get("mode", "unknown"),
                "prediction": pred_meta.get("mode", "unknown"),
                "signal": sig_meta.get("mode", "unknown"),
            },
            "generated_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        },
    }
    
    set_cached_payload(symbol, "report", payload, overall_mode, "stocksee_intelligence_core", 360)
    return payload
