"""init

Revision ID: d75fd313a675
Revises: 
Create Date: 2026-07-08 10:46:18.103402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd75fd313a675'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_reports_created_at'), 'ai_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_reports_symbol'), 'ai_reports', ['symbol'], unique=False)
    op.create_table('api_health_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_health_logs_created_at'), 'api_health_logs', ['created_at'], unique=False)
    op.create_table('market_data_cache',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('endpoint_type', sa.String(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_data_cache_created_at'), 'market_data_cache', ['created_at'], unique=False)
    op.create_index(op.f('ix_market_data_cache_endpoint_type'), 'market_data_cache', ['endpoint_type'], unique=False)
    op.create_index(op.f('ix_market_data_cache_symbol'), 'market_data_cache', ['symbol'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_articles_created_at'), 'news_articles', ['created_at'], unique=False)
    op.create_index(op.f('ix_news_articles_symbol'), 'news_articles', ['symbol'], unique=False)
    op.create_table('sentiment_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('overall_sentiment', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_scores_created_at'), 'sentiment_scores', ['created_at'], unique=False)
    op.create_index(op.f('ix_sentiment_scores_symbol'), 'sentiment_scores', ['symbol'], unique=False)
    op.create_table('source_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_logs_created_at'), 'source_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_source_logs_symbol'), 'source_logs', ['symbol'], unique=False)
    op.create_table('user_watchlists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_watchlist_user_symbol', 'user_watchlists', ['user_id', 'symbol'], unique=True)
    op.create_index(op.f('ix_user_watchlists_created_at'), 'user_watchlists', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_watchlists_symbol'), 'user_watchlists', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_watchlists_symbol'), table_name='user_watchlists')
    op.drop_index(op.f('ix_user_watchlists_created_at'), table_name='user_watchlists')
    op.drop_index('ix_user_watchlist_user_symbol', table_name='user_watchlists')
    op.drop_table('user_watchlists')
    op.drop_index(op.f('ix_source_logs_symbol'), table_name='source_logs')
    op.drop_index(op.f('ix_source_logs_created_at'), table_name='source_logs')
    op.drop_table('source_logs')
    op.drop_index(op.f('ix_sentiment_scores_symbol'), table_name='sentiment_scores')
    op.drop_index(op.f('ix_sentiment_scores_created_at'), table_name='sentiment_scores')
    op.drop_table('sentiment_scores')
    op.drop_index(op.f('ix_news_articles_symbol'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_created_at'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_market_data_cache_symbol'), table_name='market_data_cache')
    op.drop_index(op.f('ix_market_data_cache_endpoint_type'), table_name='market_data_cache')
    op.drop_index(op.f('ix_market_data_cache_created_at'), table_name='market_data_cache')
    op.drop_table('market_data_cache')
    op.drop_index(op.f('ix_api_health_logs_created_at'), table_name='api_health_logs')
    op.drop_table('api_health_logs')
    op.drop_index(op.f('ix_ai_reports_symbol'), table_name='ai_reports')
    op.drop_index(op.f('ix_ai_reports_created_at'), table_name='ai_reports')
    op.drop_table('ai_reports')
    # ### end Alembic commands ###
